name: mobile
description: GreenHealer Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  tflite_flutter: ^0.12.1
  image_picker: ^1.0.7
  image: ^4.1.3
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  get_it: ^7.6.0
  uuid: ^4.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/branding/
    - assets/images/farmer/
    - assets/images/backgrounds/
    - assets/models/
    - assets/data/
    - assets/labels.txt

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/branding/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/branding/app_logo.png"